services:
  faq-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faq-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - LOG_LEVEL=${LOG_LEVEL:-error}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pidof", "faq_bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s