version: '3.8'

services:
  faq-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faq-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - LOG_LEVEL=${LOG_LEVEL:-error}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pgrep", "faq_bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'